import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Auth/Navigation";
import "../components/Auth/Navigation.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navigation />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
